"""update

Revision ID: 17f6e5123a37
Revises: cbe02d4f41fc
Create Date: 2024-08-27 18:49:32.963332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f6e5123a37'
down_revision = 'cbe02d4f41fc'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        # Provide a name for the foreign key constraint
        batch_op.create_foreign_key('fk_sales_user_id', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        # Drop the foreign key constraint by its name
        batch_op.drop_constraint('fk_sales_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###